# Site settings
title: "Investor Pitch Me Directory"
email: "darren@chaospointadvisory.com"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://investorpitch.me" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
